### ISSUE TITLE
Using 3D-FRONT/-Future, SUNCG instead.

### ISSUE THREAD

**Issue by shinobu-x** [brownvc/fast-synth#4]
Hello, I'm thinking of using 3D-FRONT/-Future for reproduction purpose for my research to extend model. It's because of unavailability of SUNCG. To that purpose, I have following questions.

1. What need to be modified in create_dataset or other scripts? 
2. What is the data structure under {data_dir}/suncg_data/house originally (if you use SUNCG)?
3. Any experiments with 3D-FRONT/-Future?
4. How should be "ModelCategoryMapping.csv" and "ModelCategoryMapping_grains.csv"?

If you have any code to make 3D-FRONT compatible with SUNCG, it would be much time saving.
Thank you very much for your help in advance.

**Comment by kwang-ether** [comment]
1.create_dataset just calls a collection of functions that parse the individual objs, parse the layout jsons, filters data and generating appropriate renders, etc. 
2.iirc it's a bunch of json files that describes the type, model and pose of each object in the scene. you should be able to figure out exactly what I extracted from these by looking at the data processing code.
3.I know quite a few people have trained models on 3D-FRONT but i'm not sure if any of these models were made public
4.check object_data.py, it should be the only file that extracts information from the csvs. You need to label the 3D-FUTURE objects in similar ways

let me know if you have additional questions
