### ISSUE TITLE
KeyError:'parent'

### ISSUE THREAD

**Issue by JackW987** [brownvc/fast-synth#6]
Hello,I follow the deep synth scipts deal the suncg dataset,but I find the node dictionary doesn't have the 'parent' key.
I want to know how did this problem come about.Maybe some problem occur when I run the scripts, or the version of suncg case this problem?
Thanks

**Comment by kwang-ether** [comment]
It was loaded from house_relations. It's pretty much just a support hierarchy, you could compute it yourself I think

**Comment by JackW987** [comment]
> It was loaded from house_relations. It's pretty much just a support hierarchy, you could compute it yourself I think

Get it,thanks for your reply!
